### ISSUE TITLE
edge case: MessageBox clipped

### ISSUE THREAD

**Issue by dshe** [TomaszRewak/MessageBoxPositionManager#1]
The MessageBox is positioned in the center of the owner window. Usually this is fine. But in the case where the MessageBox is larger than the owner window, and the owner window is positioned at the edge of the screen, part of the MessageBox may not be visible:

<img width="375" alt="clip" src="https://user-images.githubusercontent.com/750168/107357452-09e9db80-6b0d-11eb-9a30-e4e99ae9f1b2.png">

**Comment by TomaszRewak** [comment]
Cool, thanks for reporting!

I've fixed it in the 690209bedefc80cd7bad9330f5f9c79ec02ec25a.
I've also released a new version v1.1.0 together with updating the Nuget.

**Comment by dshe** [comment]
Great. That seems to work Thanks for the speedy response!
